### ISSUE TITLE
Filtering pages

### ISSUE THREAD

**Issue by iskrisis** [sylvainjule/kirby-pagetable#16]
Hi!
Core pages has this in "ideas" but since that might take very long time i will have to solve this soon. Instead of writing it myself maybe there is chance to improve pagetable. Maybe it is too far from aim of pagetable.

Example:
I have page "project" that groups pages "outputs". The relation is defined in the "output" page - it is simple select field with query of all projects. But it would be most useful to see which outputs are linked from the project page. So instead of parent it would be awesome to define query. Not sure if it would be even possible.
```yaml
outputs:
  type: pagetable
  parent: site.find("outputs").children.filterBy('linkedToProject', page.uri)
```
More i am thinking about it it is probably better to create separate plugin. This should be read only link. All that interface wouldn't make sense.
