### ISSUE TITLE
Headline and limitOptions dropdown issue

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-pagetable#27]
![FireShot Capture 716 - Katalog - PixelShop - http___pixelshop com_panel_pages_urunler](https://user-images.githubusercontent.com/3393422/61360544-4e58bb00-a887-11e9-8850-01b9a6cd6749.png)

**Here my blueprint:**

```
sections:
    mypagetable:
        headline: Ürünler
        type: pagetable
        status: all
        image:
            cover: true
        columns:
            title:
                label: Ürün Adı
                text: '{{ page.title }}'
                width: 3/6
            price:
                label: Fiyat
                text: '{{ page.price }} / <del>{{ page.priceTag }}</del>'
                width: 1/6
            stock:
                label: Stok
                text: '{{ page.quantity.toInt }}'
                width: 1/6
            date:
                label: Tarih
                type: date
                text: '{{ page.createdAt.toDate("Y-m-d") }}'
                dateInputFormat: 'YYYY-MM-DD'
                dateOutputFormat: 'MMMM YYYY'
                width: 1/6
```

1. Do not appear `headline` that you will see in above screenshot and empty html tag in following screenshot:

![ss2](https://user-images.githubusercontent.com/3393422/61360890-05edcd00-a888-11e9-8816-e8f8cc64f8e4.png)

2. Limit Options dropdown selected item not seen like your screenshot, as if there is a css problem:

![ss](https://user-images.githubusercontent.com/3393422/61360795-d63ec500-a887-11e9-8230-d93a8478a15a.png)
