### ISSUE TITLE
CSS selector in the README does not target anything

### ISSUE THREAD

**Issue by trych** [sylvainjule/kirby-pagetable#28]
Just a quick heads up, I think there is a small error in the docs. There is this section in the `README.md`:

```css
.k-pagetable-section .category-label {
  font-size: 0.65rem;
  text-transform: uppercase;
  padding: 5px 7px;
  border-radius: 3px;
}
.k-pagetable-section .category-label[data-category="architecture"] {
  background: #d7e1e9;
}
.k-pagetable-section .category-label[data-category="culture"] {
  background: #f5e6bf;
}
.k-pagetable-section .category-label[data-category="environment"] {
  background: #cae5dd;
}
.k-pagetable-section .category-label[data-category="gastronomy"] {
  background: #e0d7dd;
}
.k-pagetable-section .category-label[data-category="science"] {
  background: #f9e9e0;
}
```

However, that does not seem to target anything in the panel. If I change all the `.k-pagetable-section` to just `.k-section`, it works again.
