### ISSUE TITLE
Translatable empty placeholder

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-pagetable#30]
It would be nice to be able to change the text when the table is empty.

```
products:
    headline: Products
    type: pagetable
    empty: You have not added any products yet
```
