### ISSUE TITLE
"Add page" leads to error

### ISSUE THREAD

**Issue by macx** [sylvainjule/kirby-pagetable#31]
The following demo template will produce an error as soon I click to add an page: `Cannot read property 'id' of null`.

```yaml
title: Test

sections:
  draft:
    type: pagetable
```

![image](https://user-images.githubusercontent.com/84112/62627657-1b579380-b92a-11e9-9389-9a4753ef2582.png)
