### ISSUE TITLE
Automatically calculated width feature

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-pagetable#32]
As in the Kirby structure field, the dynamic width feature would be very useful.

https://getkirby.com/docs/reference/panel/fields/structure#table-columns

```
columns: 
  title: 
    width: 3/5      
  images: 
    width: 1/5
  price: 
    width: 1/10
```
