### ISSUE TITLE
Custom field names do not work

### ISSUE THREAD

**Issue by trych** [sylvainjule/kirby-pagetable#34]
As soon as I add the `translations` field in my blueprint as described in the docs, suddenly my pagetable does not list any pages anymore. Any way to fix this?

Does also not matter which language I choose in the panel, the pagetable stays empty.

**Comment by sylvainjule** [comment]
You're working with the releases or got the latest code from master? Latest changes haven't been pushed into a release yet.

**Comment by trych** [comment]
The lastest code from master, actually from a while back. Did not realize there were recent changes. Will update the plugin.

**Comment by trych** [comment]
Hm. Just downloaded the current master, but the problem stays the same. The pagetable becomes empty.

**Comment by sylvainjule** [comment]
Can you share the translations options causing the issue?

**Comment by trych** [comment]
Sure, here is my complete data:

```yaml
mypagetablesection:
  headline: Projektübersicht
  type: pagetable
  status: all
  templates:
    - project
  image:
    cover: true
  columns:
    title:
      label: Name
      text: '{{ page.title }}'
      width: 1/2
    category:
      label: Category
      text: '{{ page.category.toLabel }}'
    date:
      label: Jahr
      type: date
      text: '{{ page.date.toDate("Y-m-d") }}'
      dateInputFormat: 'YYYY-MM-DD'
      dateOutputFormat: 'YYYY'
      width: 1/6
    translations:
      filterPages: Bla
```

But I also tried your options completely from the docs, to be sure to avoid typing errors, still didn't work.
