### ISSUE TITLE
Field of type toggle is empty in table when using fieldMethods

### ISSUE THREAD

**Issue by felixbridell** [sylvainjule/kirby-pagetable#35]
In my blueprint I have:
```
merchant_categories:
    type: pagetable
    headline: Handlare
    create: merchant
    status: all
    limit: 100
    columns:
        local_image_save_to_s3:
        label: S3-bucket
        text: '{{page.local_image_save_to_s3.statusLabel}}'
        type: text
        searchable: false
```

local_image_save_to_s3 is a type toggle in the subpage blueprint
```
local_image_save_to_s3:
    label: Spara produktbild till S3-bucket?
    type: toggle
    text: 
        - Nej
        - Ja
        default: false
```

Inside plugins/my-methods/index.php I have this fieldMethod:
```
Kirby::plugin('mashplan/StatuslabelField', [
  'fieldMethods' => [
      'statusLabel' => function($field) {
        $value = $field->value;
        return '<span class="status-label" data-status-type="'. $value .'">' . $value . '</span>';
      },
  ]
]);
```

This fieldMethod works fine on another field which is of type text but on this one of type toggle it is empty
