### ISSUE TITLE
Display the value of 2+ fields as text in a column 

### ISSUE THREAD

**Issue by sylvainjule** [sylvainjule/kirby-pagetable#45]
```yml
# site/blueprints/*.yml
...
  columns:
    example:
      text: '{{ page.checkboxesValues }}'
```

```php
Kirby::plugin('my/page-methods', [
    'pageMethods' => [
        'checkboxesValues' => function () {
            $first       = $this->first()->value();
            $second = $this->second()->value();
            // ...
            // do something with $first and $second if needed
            return $first . ' ' . $second;
        }
    ]
]);
```
