### ISSUE TITLE
Can't correct date output format get to work

### ISSUE THREAD

**Issue by trych** [sylvainjule/kirby-pagetable#51]
I am trying to label a column with a year that I receive from a date on the page.

My original date is formatted like this: `Earliestdate: 2019-02-06`

Following the documentation, I have set up my bluprint like this:

```php
date:
  label: Jahr
  type: date
  text: '{{ page.earliestdate("Y-m-d") }}'
  dateInputFormat: 'YYYY-MM-DD'
  dateOutputFormat: 'YYYY'
  width: 1/6
```

However, this still renders a complete date like that (no matter how I change the `dateOutputFormat`:

![20200215-013805_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/74578250-d5901d80-4f93-11ea-8328-951b305464d7.png)

Am I doing something wrong or is this a bug?

**Comment by lareusmedia** [comment]
Have you tried this yet?

`date:
  label: Jahr
  type: date
  text: '{{ page.earliestdate.toDate }}'
  dateInputFormat: 'YYYY-MM-DD'
  dateOutputFormat: 'YYYY'
  width: 1/6`

**Comment by trych** [comment]
I tried it now, both these options result in the output `Invalid date`.

**Comment by mattwolff** [comment]
I'm having the same issue. I'm unable to specify how dates are formatted. As a temporary workaround (NOT a fix), I've changed my column to be a text field `type: text`.

```
columns:
  title:
      label: Title
      text: '{{ page.title }}'
      type: text
  date:
      label: Date
      type: text
      text: '{{ page.date.toDate('M. d, Y') }}'
      # for only years like 2014 use 'Y'
      # text: '{{ page.date.toDate('Y') }}'
```
Could this have something to with how `tbl-for-kirby` handles dates?
