### ISSUE TITLE
virtual parent

### ISSUE THREAD

**Issue by felixbridell** [sylvainjule/kirby-pagetable#54]
Would be super cool if it was possible to query a "virtual parent" to list pages. So it will be possible to list pages from grandchildren or pages by template.

```
merchants:
    type: pagetable
    headline: Merchants
    create: merchant
    status: all
    limit: 100
    parent: site.index.findBy("intendedTemplate", "merchant")
```
