### ISSUE TITLE
3.7 Compatibility

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-pagetable#81]
The plugin is not yet 3.7 compatible.

**Comment by sylvainjule** [comment]
I'll probably archive this plugin with the release of 3.7, in favor of the new table layout of the Pages section.

**Comment by scsskid** [comment]
quick migration guide to 3.7 (only issues I faced)

pagetable:
```
type: pagetable
columns:
  title:
    text: '{{ page.text.upper }}'
```

kirby 3.7
```
type: pages
layout: table
columns: 
  title:
    value: '{{ page.text.upper }}'
```
